Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          NeosRulez.CookieConsent:
            - Main
      defaultLanguage: 'de'
    fusion:
      autoInclude:
        NeosRulez.CookieConsent: true
NeosRulez:
  CookieConsent:
    position: 'default'
    #position: 'top'
    #position: 'bottom-left'
    #position: 'bottom-right'
    layout: 'default'
    #layout: 'classic'
    #layout: 'edgeless'
    #layout: 'wire'
    colorBanner: '#000000'
    colorBannerText: '#FFFFFF'
    colorButton: '#999999'
    colorButtonText: '#FFFFFF'